[versions]
agp = "8.13.2"
kotlin = "2.2.0"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.1"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
sunmiPrinter = "1.0.24"
dantsu-escpos = "3.4.0"
iminPrinter = "V2.0.0.17"
jetbrainsKotlinJvm = "2.2.0"
androidxStartup = "1.2.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

androidx-startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "androidxStartup" }

printer-imin = { module = "com.github.iminsoftware:IminPrinterLibrary", version.ref = "iminPrinter" }
printer-sunmi = { module = "com.sunmi:printerlibrary", version.ref = "sunmiPrinter" }
dantsu-escpos = { module = "com.github.DantSu:ESCPOS-ThermalPrinter-Android", version.ref = "dantsu-escpos" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }

